// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUM0nzuDH5RECz3Yh2svI5Z2krZuWqegM',
    appId: '1:788608038436:web:2ec987eddb01d21ed90ab1',
    messagingSenderId: '788608038436',
    projectId: 'landlord-tenant-50a98',
    authDomain: 'landlord-tenant-50a98.firebaseapp.com',
    storageBucket: 'landlord-tenant-50a98.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3N-P5Te-szuu7RpecNzXW38KvF3KILj0',
    appId: '1:788608038436:android:a69aff55f6044ce1d90ab1',
    messagingSenderId: '788608038436',
    projectId: 'landlord-tenant-50a98',
    storageBucket: 'landlord-tenant-50a98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr-MKkAarqvdBjiTTn9CmBjjBm1ogyKJA',
    appId: '1:788608038436:ios:fc12ffc8895175d6d90ab1',
    messagingSenderId: '788608038436',
    projectId: 'landlord-tenant-50a98',
    storageBucket: 'landlord-tenant-50a98.appspot.com',
    iosClientId: '788608038436-3aonprdg6c12uhr1alpq0dtfma79b4fd.apps.googleusercontent.com',
    iosBundleId: 'com.example.landlordTenent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr-MKkAarqvdBjiTTn9CmBjjBm1ogyKJA',
    appId: '1:788608038436:ios:fc12ffc8895175d6d90ab1',
    messagingSenderId: '788608038436',
    projectId: 'landlord-tenant-50a98',
    storageBucket: 'landlord-tenant-50a98.appspot.com',
    iosClientId: '788608038436-3aonprdg6c12uhr1alpq0dtfma79b4fd.apps.googleusercontent.com',
    iosBundleId: 'com.example.landlordTenent',
  );
}
